[package]
name = "deFianlShell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
md5 = "0.7.0"
rand = "0.8.5"
des = "0.8.1"
cipher = "0.4.4"

