[package]
name = "deFianlShell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block-cipher = "0.8.0"
des = "0.8.1"
rand = "0.8.5"
base64 = "0.21.7"
openssl = "0.10.38"
md5 = "0.7.0"
